// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.28.3
// source: basic_auth.proto

package basic_auth

import (
	_ "github.com/U1traVeno/tiktok-shop/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasicAuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=Authorization,proto3" header:"Authorization" json:"Authorization,omitempty"`
	Username      string `protobuf:"bytes,2,opt,name=Username,proto3" form:"Username" json:"Username,omitempty" query:"Username"`
	Password      string `protobuf:"bytes,3,opt,name=Password,proto3" form:"Password" json:"Password,omitempty" query:"Password"`
}

func (x *BasicAuthReq) Reset() {
	*x = BasicAuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuthReq) ProtoMessage() {}

func (x *BasicAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_basic_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuthReq.ProtoReflect.Descriptor instead.
func (*BasicAuthReq) Descriptor() ([]byte, []int) {
	return file_basic_auth_proto_rawDescGZIP(), []int{0}
}

func (x *BasicAuthReq) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *BasicAuthReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuthReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BasicAuthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespBody string `protobuf:"bytes,1,opt,name=RespBody,proto3" form:"RespBody" json:"RespBody,omitempty" query:"RespBody"`
}

func (x *BasicAuthResp) Reset() {
	*x = BasicAuthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicAuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuthResp) ProtoMessage() {}

func (x *BasicAuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_basic_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuthResp.ProtoReflect.Descriptor instead.
func (*BasicAuthResp) Descriptor() ([]byte, []int) {
	return file_basic_auth_proto_rawDescGZIP(), []int{1}
}

func (x *BasicAuthResp) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

var File_basic_auth_proto protoreflect.FileDescriptor

var file_basic_auth_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x09,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a, 0x0c, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x37, 0x0a, 0x0d, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x11, 0xba, 0xbb, 0x18, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2b, 0x0a, 0x0d, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x6f, 0x64, 0x79, 0x32, 0x65, 0x0a, 0x10, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x09, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x12, 0x18, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63,
	0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x22, 0x0f, 0xca,
	0xc1, 0x18, 0x0b, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x42, 0x37,
	0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x55, 0x31, 0x74,
	0x72, 0x61, 0x56, 0x65, 0x6e, 0x6f, 0x2f, 0x74, 0x69, 0x6b, 0x74, 0x6f, 0x6b, 0x2d, 0x73, 0x68,
	0x6f, 0x70, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_basic_auth_proto_rawDescOnce sync.Once
	file_basic_auth_proto_rawDescData = file_basic_auth_proto_rawDesc
)

func file_basic_auth_proto_rawDescGZIP() []byte {
	file_basic_auth_proto_rawDescOnce.Do(func() {
		file_basic_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_basic_auth_proto_rawDescData)
	})
	return file_basic_auth_proto_rawDescData
}

var file_basic_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_basic_auth_proto_goTypes = []interface{}{
	(*BasicAuthReq)(nil),  // 0: basic_auth.BasicAuthReq
	(*BasicAuthResp)(nil), // 1: basic_auth.BasicAuthResp
}
var file_basic_auth_proto_depIdxs = []int32{
	0, // 0: basic_auth.BasicAuthService.BasicAuth:input_type -> basic_auth.BasicAuthReq
	1, // 1: basic_auth.BasicAuthService.BasicAuth:output_type -> basic_auth.BasicAuthResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_basic_auth_proto_init() }
func file_basic_auth_proto_init() {
	if File_basic_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_basic_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicAuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicAuthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_basic_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basic_auth_proto_goTypes,
		DependencyIndexes: file_basic_auth_proto_depIdxs,
		MessageInfos:      file_basic_auth_proto_msgTypes,
	}.Build()
	File_basic_auth_proto = out.File
	file_basic_auth_proto_rawDesc = nil
	file_basic_auth_proto_goTypes = nil
	file_basic_auth_proto_depIdxs = nil
}
