// Code generated by hertz generator.

package basic_auth

import (
	"context"
	basic_auth "github.com/U1traVeno/tiktok-shop/biz/model/basic_auth"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// BasicAuth .
// @router /basic_auth [GET]
func BasicAuth(ctx context.Context, c *app.RequestContext) {
	var err error
	var req basic_auth.BasicAuthReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(basic_auth.BasicAuthResp)

	resp.RespBody = "Hi, your Authorization field in the request header contains:" + req.Authorization
	c.JSON(consts.StatusOK, resp)
}
