// Code generated by hertz generator.

package main

import (
	"github.com/U1traVeno/tiktok-shop/pkg/utils"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {
	h := server.Default()
	hlog.SetLogger(utils.InitHlog())
	//hlog.Info("hello logrus")
	register(h)
	h.Spin()
}
