// Code generated by hertz generator.

package basic_auth

import (
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/basic_auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		func(ctx context.Context, c *app.RequestContext) {
			fmt.Println("rootMw here")
		},
	}
}

func _basicauthMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		basic_auth.BasicAuth(map[string]string{
			"username1": "password1",
			"username2": "password2",
			"V3n0":      "123456",
			"admin":     "admin",
		}),
	}
}
