// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	api "github.com/U1traVeno/tiktok-shop/biz/router/api"
	auth "github.com/U1traVeno/tiktok-shop/biz/router/auth"
	cart "github.com/U1traVeno/tiktok-shop/biz/router/cart"
	checkout "github.com/U1traVeno/tiktok-shop/biz/router/checkout"
	order "github.com/U1traVeno/tiktok-shop/biz/router/order"
	payment "github.com/U1traVeno/tiktok-shop/biz/router/payment"
	product "github.com/U1traVeno/tiktok-shop/biz/router/product"
	user "github.com/U1traVeno/tiktok-shop/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)

	product.Register(r)

	payment.Register(r)

	order.Register(r)

	checkout.Register(r)

	cart.Register(r)

	api.Register(r)

	auth.Register(r)

}
